### ISSUE TITLE
Buscar espacio en Santiago

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/labs2017#11]
Xa que algunha actividade farase en Santiago, atopar un sitio onde realizala

**Comment by ManuelSimon** [comment]
Si esto sigue pendiente, podéis contactar conmigo. Soy estudiante de Ingeniería informática en la USC, así que quizás os pueda ayudar a encontrar sitio en mi facultad para posibles futuras actividades.
¡Un saludo!

**Comment by castrinho8** [comment]
Pues puede ser buena idea ;) De momento creo que @ResonantWave había hablado con el Recuncho Maker, igual nos puede contar algo él!

**Comment by ResonantWave** [comment]
Hablado está, y no habría problema en principio, pero no hay nada confirmado. Si puedes conseguir un espacio fácilmente en la facultad estaría genial, así hasta podríamos hacer diferentes charlas en diferentes lugares de Santiago para llegar a más gente.

**Comment by castrinho8** [comment]
Yo me ofrezco a repetir la charla de este jueves pasado sobre JS y React en Santiago si os parece bien ;)
No se si tu javi te animas a un taller de raspy

**Comment by ResonantWave** [comment]
Por mi sin problemas :smile:

**Comment by castrinho8** [comment]
Pues poned fecha y lugar y adelante! Yo mientras no sea un jueves a la tarde, en principio a partir de las 19 puedo cualquier dia, si es un finde tengo más libertad horaria ;)

**Comment by ManuelSimon** [comment]
¿Qué material os haría falta? Proyector y enchufes me imagino... ¿algo más?

**Comment by castrinho8** [comment]
Para mi con eso y eduroam es suficiente jeje, no se si javi con las raspberrys necesita algo más pero pienso que en GPUL hay de todo ;)
Podemos ver de concretar alguna fecha
?

**Comment by ManuelSimon** [comment]
¿Cuánto llevará más o menos?
Si no dura mucho, igual podíamos verlo para el día 26 (con la semana santa en medio ha cuadrado un poco mal...) a las 19.

**Comment by castrinho8** [comment]
Pues por mi parte sería sobre hora, hora y media aprox. Lo que si nos haría falta es una mano para pegar carteles por la facultad ;)

**Comment by ResonantWave** [comment]
Todo lo que necesitamos está ya en GPUL, así que sin problema. Después para los carteles puedo ayudar yo, estoy a escasos minutos de la facultad.

**Comment by ManuelSimon** [comment]
¡Perfecto! Pues si me echáis una manita ahí para pegar algún cartel me vendría perfecto. Dime un día que puedas para quedar y ponemos alguno, @ResonantWave 
Si os parece bien ese día y hora, puedo ir reservando algún aula.

**Comment by castrinho8** [comment]
Pues por mi adelante, el miércoles 26 a las 19 ;)
A la tarde veo de publicarlo en el meetup!

**Comment by ManuelSimon** [comment]
He enviado la solicitud de reserva de un aula. Cuando reciba cualquier tipo de respuesta os informaré por aquí.
Un saludo!

**Comment by ManuelSimon** [comment]
Necesito que me digáis un número aproximado de asistentes, porfa.

**Comment by castrinho8** [comment]
En coruña estamos teniendo sobre 40 personas, yo creo que puede ser una buena cifra, no creo que sean muchos mas en Santiago ;)

**Comment by ManuelSimon** [comment]
Perfecto 👍

**Comment by castrinho8** [comment]
cuando sepas aula y hora avisa y así os puedo pasar los carteles y publicar el meetup ;)

**Comment by ManuelSimon** [comment]
Sí, lo malo es que con semana santa dudo que hasta la semana que viene sepa nada 😕

**Comment by castrinho8** [comment]
Igual podemos anunciarlo, publicar el meetup e en las redes sociales pero sin confirmar el lugar, simplemente poner que es en la Escuela Técnica y el lunes post semana santa, si se sabe algo, actualizar la info y poner los carteles. ¿Cómo lo ves? En principio no debería haber fallo por la facultad no?

**Comment by ManuelSimon** [comment]
Yo lo veo bien. Espero que no haya ningún problema con respecto a la cesión del aula... de momento no ha habido mayor problema con otros grupos, que yo sepa.
En cuanto me respondan os avisaré lo antes posible.

**Comment by ManuelSimon** [comment]
¡Aula reservada! La A.7
Un saludo.

**Comment by ResonantWave** [comment]
@ManuelSimon Para los carteles, puedo prácticamente cualquier día, lunes y miércoles por la tarde y el resto por la mañana
@castrinho8 Puedes traes la cámara de vídeo?

**Comment by ResonantWave** [comment]
Mi ordenador se volvió loco y cerré la issue sin querer :fearful:

**Comment by ManuelSimon** [comment]
Este lunes me viene bastante bien, ¿puedes?

**Comment by castrinho8** [comment]
Llevo la cámara sin fallo y también os he enviado por email el cartel en png y pdf ;)

**Comment by ResonantWave** [comment]
@ManuelSimon Sin problemas! Hora y lugar?
@castrinho8 Gracias!

**Comment by ManuelSimon** [comment]
En la entrada de la ETSE. Y hora... En principio tengo toda la tarde libre, así que cuando mejor te venga, que yo vivo cerca.

**Comment by ManuelSimon** [comment]
Ups! Estaba yo tan libre porque al ser el día del patrón de la ETSE nos dan el día libre, pero claro, me acabo de dar cuenta que la escuela tampoco abre http://www.usc.es/etse/node/9802 😂😂😅😅
Miércoles por la tarde puedo a las 20.00, ¿es posible ahí?

**Comment by castrinho8** [comment]
Por cierto, pedid factura a nombre de GPUL cuando paguéis los carteles y así luego la asociación os lo reembolsa ;)
Datos: http://www.gpul.org/node/4

**Comment by ResonantWave** [comment]
Miércoles a las 20 sin problemas!
@castrinho8 Eso ya estaba pensado :laughing::laughing:

**Comment by ManuelSimon** [comment]
Muy bien la charla. No dudéis en poneros en contacto conmigo cuando queráis dar la charla de Raspberry o cualquier otra.
También os animo a participar en las actividades que hagamos en el GDG, o incluso a colaborar si queréis -> https://www.meetup.com/gdgsantiagoes/

Keep in touch
