### ISSUE TITLE
Pedir merchandising a FSF

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/labs2017#21]
Pedir a través da web da FSF merchandising que o mandan de forma gratuita para repartir nas actividades (pedir moitas pegatinas e menos flyers)

https://fsfe.org/contribute/spreadtheword.en.html#promo-material

**Comment by ResonantWave** [comment]
Pegatinas pedidas! A ver si alguien más pide también para poder repartir pegatinas liberalmente a todo el mundo en las charlas :laughing:

**Comment by castrinho8** [comment]
Yo también he pedido unas cuantas, creo que ya podemos cerrar esta tarea ;)
