### ISSUE TITLE
Traducir dossier de sponsors a inglés

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/labs2017#22]

**Comment by ssaavedra** [comment]
¿Onde está o dossier en formato editable? Podo ao mellor botarlle un ollo esta noite.

**Comment by castrinho8** [comment]
Ahora mismo está no onwcloud de GPUL, /eventos/2016-2017/GPUL_LABS/Dossier_sponsor
Se calquera outro se ofrece a botar unha man pódollo pasar eu personalmente ;)

**Comment by ssaavedra** [comment]
Chachi :-)
