### ISSUE TITLE
Actualizar web labs

### ISSUE THREAD

**Issue by castrinho8** [gpul-labs/labs2017#26]
- Editar nueva directiva de GPUL
- Añadir a Fran Rúa como ponente Git
-

**Comment by ssaavedra** [comment]
Este é o commit no que se actualizou isto, imaxino. https://github.com/gpul-labs/labs-landing/commit/795ee1f5b3a2caf46934ba958fa35e3a7f73e30e

**Comment by castrinho8** [comment]
Yes!
