### ISSUE TITLE
¿Donde manter a landing?

### ISSUE THREAD

**Issue by ssaavedra** [gpul-labs/labs2017#31]
Debería de estar a landing no mesmo proxecto no que está agora, ou deberíamos de ter outro repo para manter a web dos labs do ano pasado, por exemplo, en 2016.labs.gpul.org ?

cc/ @gpul-labs/coordinacion

**Comment by castrinho8** [comment]
Eu son fan de mantelo como está ahora, seguindo o modelo que usan na https://fosdem.org, pero é interesante escoitar máis propostas ;)

**Comment by ssaavedra** [comment]
Non me parece mal. Pero en lugar de ter todos os ficheiros ahí igual mellor ter unha rama 2016 e facer un git-submodule co 2016, para non ter que clonar os anos anteriores se non imos a tocar nada neles (pero aínda así que se renderice ao facer a imaxe de Docker).

**Comment by ssaavedra** [comment]
Pero vale, deixalo así tamén me parece ben :-)
